overrides:
  zod: ^4.4.3
allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - unrs-resolver
